apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "car-lot.fullname" . }}
  labels:
    app: carlot-app
    {{- include "car-lot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: carlot-app
      {{- include "car-lot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: carlot-app
        {{- include "car-lot.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: carlot-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.port }}

          # HEALTH CHECKS (Critical for ALB)
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
