apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "car-lot.fullname" . }}-pv
spec:
  capacity:
    storage: {{ .Values.nfs.storage }}
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "car-lot.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.nfs.storage }}
  storageClassName: ""
  volumeName: {{ include "car-lot.fullname" . }}-pv
