apiVersion: v1
kind: Service
metadata:
  name: {{ include "car-lot.fullname" . }}
  labels:
    app: carlot-app
    {{- include "car-lot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: carlot-app
    {{- include "car-lot.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
